workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars: {} # Leere Variablen, falls keine benötigt werden
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
    publishing:
      app_store_connect:
        credentials:
          api_key: |
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWtMvovvKau16OX6p
            gySbLpM7xZNj8ZfaF14nRQCBCzegCgYIKoZIzj0DAQehRANCAARMEZbqcwSOjnaw
            /0A4Sub/jK/1vLoR0kx396mlKu88FvT53KKQwHKBtcgw8Kl49P2aLt0s1izmamxf
            3IvzUZjE
          issuer_id: 8c428024-921d-4ca4-8b0e-84c410dff42b
          key_id: HZGZ74GASG
        submit_to_testflight: true
