workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: HZGZ74GASG # Deine Key ID
          issuer_id: Bc428024-921d-4ca4-8b0e-84c410dff42b # Deine Issuer ID
          private_key: Encrypted(...) # Codemagic verschlüsselt die Datei automatisch
        submit_to_testflight: true
